//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.23 at 05:26:53 PM GMT+01:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ashref.com/soap/ws/countryDetails", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ashref.soap.ws.countrydetails;
